/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        outline: "#82807b",
        "primary-dim": "#973c00",
        tertiary: "#8c5900",
        "on-secondary-fixed": "#6a100d",
        "tertiary-container": "#feb246",
        "inverse-surface": "#0f0e0b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#4f1c00",
        "on-tertiary-container": "#563500",
        surface: "#fffbff",
        error: "#be2d06",
        "error-container": "#f95630",
        "on-surface-variant": "#666460",
        "tertiary-fixed": "#feb246",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#9f9d97",
        "outline-variant": "#bcb9b3",
        "secondary-container": "#ffc3bc",
        "surface-container-highest": "#ebe8e0",
        "secondary-fixed": "#ffc3bc",
        "on-error-container": "#520c00",
        "surface-dim": "#e6e2da",
        "on-primary": "#ffffff",
        "surface-container-low": "#fdf9f2",
        "on-tertiary": "#ffffff",
        "surface-variant": "#ebe8e0",
        "secondary-dim": "#9c352c",
        "on-primary-container": "#401500",
        "tertiary-fixed-dim": "#eea439",
        "primary-fixed": "#ff7a2f",
        "on-surface": "#393834",
        background: "#fffbff",
        "secondary-fixed-dim": "#ffb0a6",
        "on-tertiary-fixed-variant": "#623d00",
        secondary: "#ac4137",
        "on-background": "#393834",
        "surface-container": "#f7f3ec",
        "primary-container": "#ff7a2f",
        "on-secondary-fixed-variant": "#922d26",
        "on-tertiary-fixed": "#3a2300",
        "surface-tint": "#aa4500",
        primary: "#aa4500",
        "inverse-primary": "#fe6b00",
        "surface-bright": "#fffbff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#f1ede6",
        "error-dim": "#b92902",
        "primary-fixed-dim": "#f66700",
        "on-secondary-container": "#85241d",
        "tertiary-dim": "#7c4f00",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        body: ['"Be Vietnam Pro"', "system-ui", "sans-serif"],
        label: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
